name: Deploy Node.js App to AWS

on:
  push:
    branches:
      - main  # Deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/node-app || git clone https://github.com/kallol-khatua/Express-JS-AWS-deploy.git node-app && cd node-app
            git pull origin main
            npm install
            pm2 restart all || pm2 start app.js --name "node-app"
            exit
          EOF
