name: Deploy Node.js App to AWS

on:
  push:
    branches:
      - main  # Deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            
            # Setup the Node.js app
            cd ~/node-app
            git pull origin main
            npm install
            
            # Ensure PM2 is installed
            pm2 -v || sudo npm install -g pm2
            
            # Restart or start the app with PM2
            pm2 restart node-app || pm2 start app.js --name "node-app"
            pm2 save
            pm2 startup systemd
            
            # Configure Nginx            
            # sudo ln -sf /etc/nginx/sites-available/node-app /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
            
            exit
          EOF
